
echo "Tipos de redirecionadores:"

echo " "
echo ">: grava a saída padrão de um comando em um arquivo;"
echo " "
echo "exemplo: emanuel@gaj ~ cat arq2 > arq1"
echo " "
echo ">>: grava a saída padrão de um comando no final de um arquivo, sem apagar seu conteúdo;"
echo " "
echo "exemplo: emanuel@gaj ~ cat arq2 >> arq1"
echo " "
echo "2>: grava a saída de erro de um comando em um arquivo;"
echo " "
echo "exemplo: emanuel@gaj ~ ls arq4 2> arq3"
echo " "
echo "2>>: grava a saída de erro de um comando no final de um arquivo, sem apagar seu conteúdo;"
echo " "
echo "exemplo: emanuel@gaj ~ ls arq4 2>> arq3"
echo " "
echo "&>: grava a saída padrão e a saída de erro de um comando em um arquivo;"
echo " "
echo "exemplo: emanuel@gaj ~ cat arq1 &> arq2"
echo " "
echo "&>>: grava a saída padrão e a saída de erro de um comando no final de um arquivo, sem apagar seu conteúdo;"
echo " "
echo "exemplo: emanuel@gaj ~ ls arq2 &>> arq3"
echo " "
echo "<: grava a entrada de um comando em um arquivo;"
echo " "
echo "exemplo: emanuel@gaj ~ ls < arq2"
echo " "
echo "<<: permite que o usuário digite um arquivo no qual será gravada a entrada de um comando;"
echo " "
echo "exemplo: emanuel@gaj ~ wc -l << DATA"
echo " "
echo "<<<: permite que o usuário digite uma string na qual será gravada a entrada de um comando;"
echo " "
echo "exemplo: emanuel@gaj ~ wc -c <<< '2 + 3' "
echo " "
echo "|: grava a saída de um comando na entrada de outro comando;"
echo " " 
echo "exemplo: emanuel@gaj ~ echo 'arq2' | tee"
